[package]
name = "jaspy-nexus"
version = "2.1.2"
authors = ["Antti Tönkyrä <daedalus@pingtimeout.net>"]

[dependencies]
config = "*"
dotenv = "*"
rocket = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
diesel = { version = "*", features = ["postgres"] }
r2d2 = "*"
r2d2-diesel = "*"
time = "*"
rumqtt = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

