version: '3'

services:
  discover:
    build:
      context: ./discover
    env_file:
      - jaspy.env
  nexus:
    build:
      context: ./nexus
    env_file:
      - jaspy.env
    depends_on:
      - db
  pinger:
    build:
      context: ./pinger
    env_file:
      - jaspy.env
  poller:
    build:
      context: ./poller
    env_file:
      - jaspy.env
  snmptrapd-reader:
    build:
      context: ./snmptrapd-reader
    env_file:
      - jaspy.env
    ports:
      - "162:162/udp"
  weathermap:
    build:
      context: ./weathermap
    ports:
      - "8080:80"
    env_file:
      - jaspy.env
  snmpbot:
    image: qmsk/snmpbot
    logging:
      driver: none
    env_file:
      - jaspy.env
    network_mode: host
    volumes:
      - ./snmpbot/mibs:/opt/qmsk/snmpbot/mibs
  db:
    image: postgres:11.2-alpine
