[package]
name = "jaspy-poller"
version = "2.1.0"
authors = ["Antti Tönkyrä <daedalus@pingtimeout.net>"]

[dependencies]
reqwest = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
rand = "*"
config = "*"
