[package]
name = "jaspy-snmptrapd-reader"
version = "2.2.0"
authors = ["Antti Tönkyrä <daedalus@pingtimeout.net>"]

[dependencies]
config = "*"
reqwest = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
nix = "*"
