[package]
name = "jaspy-pinger"
version = "2.1.0"
authors = ["Antti Tönkyrä <daedalus@pingtimeout.net>"]

[dependencies]
config = "*"
oping = "*"
reqwest = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
