[package]
name = "jaspy-pinger"
version = "2.2.0"
authors = ["Antti Tönkyrä <daedalus@pingtimeout.net>"]

[dependencies]
config = "*"
oping = "*"
reqwest = { version = "*", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
